name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up .env file
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
        run: |
          echo "API_TYPE=azure" >> .env
          echo "GPT_MODEL=gpt-4o-mini" >> .env
          echo "GPT_API_VERSION=2024-08-01-preview" >> .env
          echo "EMBEDDING_MODEL=text-embedding-3-small" >> .env
          echo "EMBEDDING_API_VERSION=2023-05-15" >> .env
          echo "ENDPOINT=https://ai4se-openai.openai.azure.com/" >> .env
          echo "AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY" >> .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: darshanscripts/domain-modelling-copilot-temp:latest
          cache-from: type=registry,ref=darshanscripts/domain-modelling-copilot-temp:latest
          cache-to: type=inline